title: Codeaholics FEb
author: 3dd13
description: 3dd13 is a Ruby On Rails / Scala / Java Developer and Penetration Tester working at Thought Sauce. Familiar with agile developement practices
email: tatonlto@gmail.com
venue: boot.hk
date: 2011-02-24

destination: pages
permalink: /:year/:month/:day/:title
auto: on
pygments: true
