Codeaholics Hong Kong Sharing Feb 2011
===============

talks about the architecture of my program, and performance tuning works I did.

generated by <a href="https://github.com/jingweno/jekyll_and_hyde">jekyll_and_hyde</a>

deployed with <a href="https://github.com/bry4n/rack-jekyll/">rack-jekyll</a>